[package]
name = "http-tunnel"
version = "0.5.0"
edition = "2021"
authors = ["Yujia Qiao <code@rapiz.me>", "jiangood"]
description = "A secure, stable and high-performance HTTP reverse proxy for NAT traversal"
license = "Apache-2.0"
repository = "https://github.com/jiangood/http-tunnel"
readme = "README.md"
build = "build.rs"
include = ["src/**/*", "LICENSE", "README.md", "build.rs"]

[features]
default = [
    "server",
    "client",
]

# Run as a server
server = []
# Run as a client
client = []

# Feature to enable tokio-console. Disabled by default.
# Don't enable it unless for debugging purposes.
console = ["console-subscriber", "tokio/tracing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = true

[profile.bench]
debug = 1

[profile.minimal]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0", features = ["derive", "env"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
sha2 = "0.10"
bincode = "1"
lazy_static = "1.4"
hex = "0.4"
rand = "0.8"
backoff = { version = "0.4", features = ["tokio"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fdlimit = "0.2"
console-subscriber = { version = "0.1", optional = true, features = [
    "parking_lot",
] }
atty = "0.2"

[build-dependencies]
vergen = { version = "7.4.2", default-features = false, features = [
    "build",
    "git",
    "cargo",
] }
anyhow = "1.0"
